In [1]:
from bs4 import BeautifulSoup
import requests

In [5]:
# Write a python program to display IMDB's Top rated 100 Indian movies' data (i.e. name, rating, year of release) and make data frame.

# Write a python program to display IMDB's Top rated 100 movies' data (i.e. name, rating, year of release) and make data frame.

page = requests.get('https://www.imdb.com/india/top-rated-indian-movies/') # Send request to webserver to get the source code

ind_soup = BeautifulSoup(page.content) # To Assign the page content to the variable soup
ind_movietitle = ind_soup.find_all('td', class_="titleColumn")
ind_movietitle

ind_movies = []

for ind_movie in ind_movietitle:
    ind_movie = ind_movie.get_text().replace('\n', "")
    ind_movie = ind_movie.strip(" ")
    ind_movies.append(ind_movie)
ind_movies[:100]
    
ind_scraped_ratings = ind_soup.find_all('td', class_='ratingColumn imdbRating')
ind_ratings = []
for ind_rating in ind_scraped_ratings:
    ind_rating = ind_rating.get_text().replace('\n', '')
    ind_ratings.append(ind_rating)
ind_ratings

import pandas as pd
ind_data = pd.DataFrame()
ind_data['Movie Names'] = ind_movies[:100]
ind_data['Ratings'] = ind_ratings[:100]
ind_data

                               Movie Names Ratings
0                   1.      Jai Bhim(2021)     8.4
1                 2.      Anbe Sivam(2003)     8.4
2                    3.      Golmaal(1979)     8.4
3                    4.      Nayakan(1987)     8.4
4          5.      Pariyerum Perumal(2018)     8.4
..                                     ...     ...
95          96.      Rang De Basanti(2006)     8.0
96                   97.      Masaan(2015)     8.0
97           98.      Dil Chahta Hai(2001)     8.0
98  99.      Maheshinte Prathikaaram(2016)     8.0
99                 100.      Kahaani(2012)     8.0

[100 rows x 2 columns]